apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-html-app
  template:
    metadata:
      labels:
        app: simple-html-app
    spec:
      containers:
        - name: simple-html-app
          image: simple-html-app:latest
          ports:
            - containerPort: 80

