apiVersion: v1
kind: Service
metadata:
  name: simple-html-app-service
spec:
  selector:
    app: simple-html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Use NodePort or ClusterIP for non-cloud setups

